In [1]:
import os
import pandas as pd

In [2]:
text_path = '/Users/tyler/Datasets/phi-macronized/cicero/'

In [3]:
texts = [text[:-4].replace('_', ' ') for text in os.listdir(text_path)]

In [4]:
rhythm_data = pd.read_csv('../data/cicero_rhythms_v1.csv')
rhythm_data = rhythm_data.drop(columns=['Unnamed: 0'])
rhythm_data.head()

,------------x,-----------ux,-----------x,----------u-x,----------uux,----------ux,----------x,---------u--x,---------u-ux,---------u-x,...,uuuuuuuuuuux,uuuuuuuuux,uuuuuuuux,uuuuuuux,uuuuuux,uuuuux,uuuux,uuux,uux,ux
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,8.0,4.0
1,1.0,2.0,0.0,1.0,0.0,1.0,0.0,4.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df = pd.DataFrame({ 'title': texts })
df.head()

                 title
0   pro roscio comoedo
1             lucullus
2          pro fonteio
3  epistulae ad brutum
4            pro balbo

In [6]:
df['total clausulae'] = rhythm_data.sum(axis=1)
df.head()

                 title  total clausulae
0   pro roscio comoedo            980.0
1             lucullus           2328.0
2          pro fonteio            548.0
3  epistulae ad brutum           1382.0
4            pro balbo            696.0

In [7]:
pure_cretic_trochee = rhythm_data[[col for col in rhythm_data.columns if '-u--x' in col]].copy()
pure_cretic_trochee.head()

,---------u--x,--------u--x,-------u--x,-------u-u--x,------u--u--x,------u--x,------u-u--x,------uu-u--x,-----u---u--x,-----u--u--x,...,uuuuu----u--x,uuuuu---u--x,uuuuu--u--x,uuuuu--u-u--x,uuuuu-u--u--x,uuuuu-uu-u--x,uuuuuu---u--x,uuuuuu-u-u--x,uuuuuuu--u--x,uuuuuuuu-u--x
0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,2.0,2.0,0.0,0.0,3.0,3.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df['pure cretic trochee (-u--x)'] = pure_cretic_trochee.sum(axis=1)
df.head()

                 title  total clausulae  pure cretic trochee (-u--x)
0   pro roscio comoedo            980.0                         55.0
1             lucullus           2328.0                        155.0
2          pro fonteio            548.0                         48.0
3  epistulae ad brutum           1382.0                         78.0
4            pro balbo            696.0                         79.0

In [9]:
cretic_trochee_res_1_1 = rhythm_data[[col for col in rhythm_data.columns if 'uuu--x' in col]].copy()
cretic_trochee_res_1_1.head()

,-------uuu--x,------uuu--x,------uuuu--x,-----u-uuu--x,-----uuu--x,-----uuuu--x,-----uuuuu--x,----u--uuu--x,----u-uuuu--x,----uu-uuu--x,...,uuuu--x,uuuu-u-uuu--x,uuuu-uuuuu--x,uuuuu--uuu--x,uuuuu--x,uuuuu-uuuu--x,uuuuuu--x,uuuuuu-uuu--x,uuuuuuu--x,uuuuuuuuuu--x
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df['cretic trochee 1 res (uuu--x)'] = cretic_trochee_res_1_1.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x)
0,pro roscio comoedo,980.0,55.0,9.0
1,lucullus,2328.0,155.0,30.0
2,pro fonteio,548.0,48.0,7.0
3,epistulae ad brutum,1382.0,78.0,19.0
4,pro balbo,696.0,79.0,5.0

In [11]:
cretic_trochee_res_1_2 = rhythm_data[[col for col in rhythm_data.columns if '-uuu-x' in col]].copy()
cretic_trochee_res_1_2.head()

,--------uuu-x,-------uuu-x,------u-uuu-x,------uuu-x,-----u--uuu-x,-----u-uuu-x,-----uu-uuu-x,-----uuu-x,----u---uuu-x,----u--uuu-x,...,uuuu---uuu-x,uuuu--u-uuu-x,uuuu-u--uuu-x,uuuu-uu-uuu-x,uuuu-uuu-x,uuuuu---uuu-x,uuuuu--uuu-x,uuuuu-u-uuu-x,uuuuuu--uuu-x,uuuuuuu-uuu-x
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,0.0,2.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df['cretic trochee 1 res (-uuu-x)'] = cretic_trochee_res_1_2.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0
1,lucullus,2328.0,155.0,30.0,55.0
2,pro fonteio,548.0,48.0,7.0,18.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0
4,pro balbo,696.0,79.0,5.0,25.0

In [13]:
cretic_trochee_res_1_3 = rhythm_data[[col for col in rhythm_data.columns if '-u-uux' in col]].copy()
cretic_trochee_res_1_3.head()

,--------u-uux,-------u-uux,------u-u-uux,------u-uux,-----u--u-uux,-----u-u-uux,-----u-uux,-----uu-u-uux,----u---u-uux,----u--u-uux,...,uuu-u-uux,uuu-uu--u-uux,uuu-uuu-u-uux,uuuu----u-uux,uuuu--u-u-uux,uuuu-u-uux,uuuuu---u-uux,uuuuu-u-u-uux,uuuuuu--u-uux,uuuuuuu-u-uux
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
df['cretic trochee 1 res (-u-uux)'] = cretic_trochee_res_1_3.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0

In [15]:
df['cretic trochee 1 res total'] = df[[col for col in df.columns if 'cretic trochee 1 res' in col]].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0

In [16]:
cretic_trochee_res_2_1 = rhythm_data[[col for col in rhythm_data.columns if 'uuuuu-x' in col]].copy()
cretic_trochee_res_2_1.head()

,------uuuuu-x,-----uuuuu-x,-----uuuuuu-x,----u-uuuuu-x,----uuuuu-x,----uuuuuuu-x,---u--uuuuu-x,---u-uuuuu-x,---u-uuuuuu-x,---uu-uuuuu-x,...,uuu--uuuuuu-x,uuu-u-uuuuu-x,uuu-uuuuu-x,uuu-uuuuuuu-x,uuuu--uuuuu-x,uuuu-uuuuuu-x,uuuuu-uuuuu-x,uuuuu-x,uuuuuu-x,uuuuuuuuu-x
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
df['cretic trochee 2 res (uuuuu-x)'] = cretic_trochee_res_2_1.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0

In [18]:
cretic_trochee_res_2_2 = rhythm_data[[col for col in rhythm_data.columns if 'uuu-uux' in col]].copy()
cretic_trochee_res_2_2.head()

,------uuu-uux,-----uuuu-uux,----u-uuu-uux,----uuu-uux,----uuuuu-uux,---u--uuu-uux,---u-uuu-uux,---u-uuuu-uux,---uu-uuu-uux,---uuu-uux,...,uuu-u-uuu-uux,uuu-uuu-uux,uuu-uuuuu-uux,uuu-uux,uuuu--uuu-uux,uuuu-uuuu-uux,uuuu-uux,uuuuu-uuu-uux,uuuuu-uux,uuuuuu-uux
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df['cretic trochee 2 res (uuu-uux)'] = cretic_trochee_res_2_2.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0

In [20]:
cretic_trochee_res_2_3 = rhythm_data[[col for col in rhythm_data.columns if '-uuuuux' in col]].copy()
cretic_trochee_res_2_3.head()

,-------uuuuux,-----u-uuuuux,----u--uuuuux,----uu-uuuuux,---u---uuuuux,---u-u-uuuuux,---u-uuuuux,---uu--uuuuux,---uuu-uuuuux,---uuuuux,...,uu-uu--uuuuux,uu-uuu-uuuuux,uu-uuuuux,uuu----uuuuux,uuu--u-uuuuux,uuu-uu-uuuuux,uuu-uuuuux,uuuu---uuuuux,uuuuu-uuuuux,uuuuuu-uuuuux
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
df['cretic trochee 2 res (-uuuuux)'] = cretic_trochee_res_2_3.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0

In [22]:
df['cretic trochee 2 res total'] = df[[col for col in df.columns if 'cretic trochee 2 res' in col]].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0

In [23]:
df['cretic trochee pure+res total'] = df[['pure cretic trochee (-u--x)', 'cretic trochee 1 res total', 'cretic trochee 2 res total']].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0

In [24]:
cretic_trochee_chor = rhythm_data[[col for col in rhythm_data.columns if '-uu--x' in col]].copy()
cretic_trochee_chor.head()

,--------uu--x,------u-uu--x,------uu--x,-----u--uu--x,-----u-uu--x,-----uu--x,-----uu-uu--x,----u---uu--x,----u--uu--x,----u-u-uu--x,...,uuu-uu--uu--x,uuu-uu--x,uuu-uu-uu--x,uuu-uuu-uu--x,uuuu----uu--x,uuuu--u-uu--x,uuuu-u--uu--x,uuuu-uu-uu--x,uuuuu--uu--x,uuuuuu--uu--x
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df['cretic trochee choriambic res'] = cretic_trochee_chor.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0

In [26]:
cretic_trochee_chor_res_1 = rhythm_data[[col for col in rhythm_data.columns if 'uuuu--x' in col]].copy()
cretic_trochee_chor_res_1.head()

,------uuuu--x,-----uuuu--x,-----uuuuu--x,----u-uuuu--x,----uuuu--x,----uuuuuu--x,---u--uuuu--x,---u-uuuuu--x,---uu-uuuu--x,---uuuu--x,...,uuu-uuuu--x,uuu-uuuuuu--x,uuuu--uuuu--x,uuuu--x,uuuu-uuuuu--x,uuuuu--x,uuuuu-uuuu--x,uuuuuu--x,uuuuuuu--x,uuuuuuuuuu--x
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
df['cretic trochee chor 1 res (uuuu--x)'] = cretic_trochee_chor_res_1.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0

In [28]:
cretic_trochee_chor_res_2 = rhythm_data[[col for col in rhythm_data.columns if '-uuuu-x' in col]].copy()
cretic_trochee_chor_res_2.head()

,-------uuuu-x,-----u-uuuu-x,----u--uuuu-x,----uu-uuuu-x,----uuuu-x,---u---uuuu-x,---u--uuuu-x,---u-u-uuuu-x,---u-uuuu-x,---uu--uuuu-x,...,uu-u-uuuu-x,uu-uu--uuuu-x,uu-uuuu-x,uuu----uuuu-x,uuu--u-uuuu-x,uuu-u--uuuu-x,uuu-uu-uuuu-x,uuuu---uuuu-x,uuuu-u-uuuu-x,uuuuuu-uuuu-x
0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df['cretic trochee chor 1 res (-uuuu-x)'] = cretic_trochee_chor_res_2.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0,4.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0,11.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0,0.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0,3.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0,0.0

In [30]:
cretic_trochee_chor_res_3 = rhythm_data[[col for col in rhythm_data.columns if '-uu-uux' in col]].copy()
cretic_trochee_chor_res_3.head()

,-------uu-uux,------uu-uux,-----u-uu-uux,-----uu-uux,----u--uu-uux,----uu-uu-uux,----uu-uux,---u---uu-uux,---u-u-uu-uux,---u-uu-uux,...,uuu--u-uu-uux,uuu--uu-uux,uuu-u--uu-uux,uuu-uu-uu-uux,uuu-uu-uux,uuuu---uu-uux,uuuu--uu-uux,uuuu-u-uu-uux,uuuuu--uu-uux,uuuuuu-uu-uux
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
df['cretic trochee chor 1 res (-uu-uux)'] = cretic_trochee_chor_res_3.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0,4.0,3.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0,11.0,5.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0,0.0,1.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0,3.0,4.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0,0.0,0.0

In [32]:
df['cretic trochee chor 1 res total'] = df[[col for col in df.columns if 'cretic trochee chor 1 res' in col]].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0,4.0,3.0,9.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0,11.0,5.0,18.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0,0.0,1.0,1.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0,3.0,4.0,9.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0,0.0,0.0,4.0

In [33]:
df['cretic trochee choriambic total'] = df[['cretic trochee choriambic res', 'cretic trochee chor 1 res total']].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0,4.0,3.0,9.0,17.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0,11.0,5.0,18.0,25.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0,0.0,1.0,1.0,4.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0,3.0,4.0,9.0,19.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0,0.0,0.0,4.0,4.0

In [34]:
cretic_trochee_ep_res = rhythm_data[[col for col in rhythm_data.columns if '-u---x' in col]].copy()
cretic_trochee_ep_res.head()

,--------u---x,-------u---x,------u---x,------u-u---x,-----u---x,-----u--u---x,-----u-u---x,-----uu-u---x,----u---u---x,----u---x,...,uuuu--u-u---x,uuuu-u---x,uuuu-u--u---x,uuuu-u-u---x,uuuu-uu-u---x,uuuuu--u---x,uuuuu-u---x,uuuuu-u-u---x,uuuuuu--u---x,uuuuuuu-u---x
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
df['cretic trochee epitrite res'] = cretic_trochee_ep_res.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0,4.0,3.0,9.0,17.0,23.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0,11.0,5.0,18.0,25.0,24.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0,0.0,1.0,1.0,4.0,6.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0,3.0,4.0,9.0,19.0,18.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0,0.0,0.0,4.0,4.0,2.0

In [36]:
cretic_trochee_ep_res_1 = rhythm_data[[col for col in rhythm_data.columns if 'uuu---x' in col]].copy()
cretic_trochee_ep_res_1.head()

,------uuu---x,-----uuu---x,-----uuuu---x,----u-uuu---x,----uuu---x,----uuuu---x,----uuuuu---x,---u--uuu---x,---u-uuu---x,---u-uuuu---x,...,uuu--uuuu---x,uuu-u-uuu---x,uuu-uuuuu---x,uuuu---x,uuuu--uuu---x,uuuu-uuuu---x,uuuuu---x,uuuuu-uuu---x,uuuuuuu---x,uuuuuuuuu---x
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
df['cretic trochee ep 1 res (uuu---x)'] = cretic_trochee_ep_res_1.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),cretic trochee 2 res total,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,7.0,93.0,8.0,2.0,4.0,3.0,9.0,17.0,23.0,4.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,9.0,267.0,7.0,2.0,11.0,5.0,18.0,25.0,24.0,6.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,1.0,77.0,3.0,0.0,0.0,1.0,1.0,4.0,6.0,0.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,9.0,143.0,10.0,2.0,3.0,4.0,9.0,19.0,18.0,3.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,3.0,119.0,0.0,4.0,0.0,0.0,4.0,4.0,2.0,2.0

In [38]:
cretic_trochee_ep_res_2 = rhythm_data[[col for col in rhythm_data.columns if '-uuu--x' in col]].copy()
cretic_trochee_ep_res_2.head()

,-------uuu--x,------uuu--x,-----u-uuu--x,-----uuu--x,----u--uuu--x,----uu-uuu--x,----uuu--x,---u---uuu--x,---u--uuu--x,---u-u-uuu--x,...,uuu---uuu--x,uuu--u-uuu--x,uuu--uuu--x,uuu-u--uuu--x,uuu-uu-uuu--x,uuu-uuu--x,uuuu---uuu--x,uuuu-u-uuu--x,uuuuu--uuu--x,uuuuuu-uuu--x
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
df['cretic trochee ep 1 res (-uuu--x)'] = cretic_trochee_ep_res_2.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),...,cretic trochee pure+res total,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x),cretic trochee ep 1 res (-uuu--x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,...,93.0,8.0,2.0,4.0,3.0,9.0,17.0,23.0,4.0,6.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,...,267.0,7.0,2.0,11.0,5.0,18.0,25.0,24.0,6.0,26.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,...,77.0,3.0,0.0,0.0,1.0,1.0,4.0,6.0,0.0,6.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,...,143.0,10.0,2.0,3.0,4.0,9.0,19.0,18.0,3.0,16.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,...,119.0,0.0,4.0,0.0,0.0,4.0,4.0,2.0,2.0,0.0

In [40]:
cretic_trochee_ep_res_3 = rhythm_data[[col for col in rhythm_data.columns if '-u-uu-x' in col]].copy()
cretic_trochee_ep_res_3.head()

,-------u-uu-x,------u-uu-x,-----u-u-uu-x,-----u-uu-x,----u--u-uu-x,----u-u-uu-x,----u-uu-x,----uu-u-uu-x,---u---u-uu-x,---u--u-uu-x,...,uu-u-uu-x,uu-uu--u-uu-x,uu-uuu-u-uu-x,uuu----u-uu-x,uuu--u-u-uu-x,uuu-u--u-uu-x,uuu-u-uu-x,uuu-uu-u-uu-x,uuuu---u-uu-x,uuuuuu-u-uu-x
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
df['cretic trochee ep 1 res (-u-uu-x)'] = cretic_trochee_ep_res_3.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),...,cretic trochee choriambic res,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x),cretic trochee ep 1 res (-uuu--x),cretic trochee ep 1 res (-u-uu-x)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,...,8.0,2.0,4.0,3.0,9.0,17.0,23.0,4.0,6.0,4.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,...,7.0,2.0,11.0,5.0,18.0,25.0,24.0,6.0,26.0,5.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,...,3.0,0.0,0.0,1.0,1.0,4.0,6.0,0.0,6.0,1.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,...,10.0,2.0,3.0,4.0,9.0,19.0,18.0,3.0,16.0,10.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,...,0.0,4.0,0.0,0.0,4.0,4.0,2.0,2.0,0.0,0.0

In [42]:
cretic_trochee_ep_res_4 = rhythm_data[[col for col in rhythm_data.columns if '-u--uux' in col]].copy()
cretic_trochee_ep_res_4.head()

,-------u--uux,------u--uux,-----u--uux,-----u-u--uux,----u--u--uux,----u--uux,----u-u--uux,----uu-u--uux,---u---u--uux,---u--u--uux,...,uu-uu--u--uux,uu-uuu-u--uux,uuu----u--uux,uuu--u--uux,uuu--u-u--uux,uuu-u--u--uux,uuu-uu-u--uux,uuuu---u--uux,uuuu-u-u--uux,uuuuu--u--uux
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
df['cretic trochee ep 1 res (-u--uux)'] = cretic_trochee_ep_res_4.sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),...,cretic trochee chor 1 res (uuuu--x),cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x),cretic trochee ep 1 res (-uuu--x),cretic trochee ep 1 res (-u-uu-x),cretic trochee ep 1 res (-u--uux)
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,...,2.0,4.0,3.0,9.0,17.0,23.0,4.0,6.0,4.0,3.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,...,2.0,11.0,5.0,18.0,25.0,24.0,6.0,26.0,5.0,5.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,4.0,6.0,0.0,6.0,1.0,1.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,...,2.0,3.0,4.0,9.0,19.0,18.0,3.0,16.0,10.0,11.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,...,4.0,0.0,0.0,4.0,4.0,2.0,2.0,0.0,0.0,1.0

In [44]:
df['cretic trochee ep 1 res total'] = df[[col for col in df.columns if 'cretic trochee ep 1 res' in col]].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),...,cretic trochee chor 1 res (-uuuu-x),cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x),cretic trochee ep 1 res (-uuu--x),cretic trochee ep 1 res (-u-uu-x),cretic trochee ep 1 res (-u--uux),cretic trochee ep 1 res total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,...,4.0,3.0,9.0,17.0,23.0,4.0,6.0,4.0,3.0,17.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,...,11.0,5.0,18.0,25.0,24.0,6.0,26.0,5.0,5.0,42.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,...,0.0,1.0,1.0,4.0,6.0,0.0,6.0,1.0,1.0,8.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,...,3.0,4.0,9.0,19.0,18.0,3.0,16.0,10.0,11.0,40.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,...,0.0,0.0,4.0,4.0,2.0,2.0,0.0,0.0,1.0,3.0

In [45]:
df['cretic trochee epitrite total'] = df[['cretic trochee epitrite res', 'cretic trochee ep 1 res total']].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),...,cretic trochee chor 1 res (-uu-uux),cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x),cretic trochee ep 1 res (-uuu--x),cretic trochee ep 1 res (-u-uu-x),cretic trochee ep 1 res (-u--uux),cretic trochee ep 1 res total,cretic trochee epitrite total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,...,3.0,9.0,17.0,23.0,4.0,6.0,4.0,3.0,17.0,40.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,...,5.0,18.0,25.0,24.0,6.0,26.0,5.0,5.0,42.0,66.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,...,1.0,1.0,4.0,6.0,0.0,6.0,1.0,1.0,8.0,14.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,...,4.0,9.0,19.0,18.0,3.0,16.0,10.0,11.0,40.0,58.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,...,0.0,4.0,4.0,2.0,2.0,0.0,0.0,1.0,3.0,5.0

In [46]:
df.columns

Index(['title', 'total clausulae', 'pure cretic trochee (-u--x)',
       'cretic trochee 1 res (uuu--x)', 'cretic trochee 1 res (-uuu-x)',
       'cretic trochee 1 res (-u-uux)', 'cretic trochee 1 res total',
       'cretic trochee 2 res (uuuuu-x)', 'cretic trochee 2 res (uuu-uux)',
       'cretic trochee 2 res (-uuuuux)', 'cretic trochee 2 res total',
       'cretic trochee pure+res total', 'cretic trochee choriambic res',
       'cretic trochee chor 1 res (uuuu--x)',
       'cretic trochee chor 1 res (-uuuu-x)',
       'cretic trochee chor 1 res (-uu-uux)',
       'cretic trochee chor 1 res total', 'cretic trochee choriambic total',
       'cretic trochee epitrite res', 'cretic trochee ep 1 res (uuu---x)',
       'cretic trochee ep 1 res (-uuu--x)',
       'cretic trochee ep 1 res (-u-uu-x)',
       'cretic trochee ep 1 res (-u--uux)', 'cretic trochee ep 1 res total',
       'cretic trochee epitrite total'],
      dtype='object')

In [48]:
df['cretic trochee total'] = df[['cretic trochee pure+res total', 'cretic trochee choriambic total', 'cretic trochee epitrite total']].copy().sum(axis=1)
df.head()

,title,total clausulae,pure cretic trochee (-u--x),cretic trochee 1 res (uuu--x),cretic trochee 1 res (-uuu-x),cretic trochee 1 res (-u-uux),cretic trochee 1 res total,cretic trochee 2 res (uuuuu-x),cretic trochee 2 res (uuu-uux),cretic trochee 2 res (-uuuuux),...,cretic trochee chor 1 res total,cretic trochee choriambic total,cretic trochee epitrite res,cretic trochee ep 1 res (uuu---x),cretic trochee ep 1 res (-uuu--x),cretic trochee ep 1 res (-u-uu-x),cretic trochee ep 1 res (-u--uux),cretic trochee ep 1 res total,cretic trochee epitrite total,cretic trochee total
0,pro roscio comoedo,980.0,55.0,9.0,11.0,11.0,31.0,2.0,4.0,1.0,...,9.0,17.0,23.0,4.0,6.0,4.0,3.0,17.0,40.0,150.0
1,lucullus,2328.0,155.0,30.0,55.0,18.0,103.0,2.0,3.0,4.0,...,18.0,25.0,24.0,6.0,26.0,5.0,5.0,42.0,66.0,358.0
2,pro fonteio,548.0,48.0,7.0,18.0,3.0,28.0,1.0,0.0,0.0,...,1.0,4.0,6.0,0.0,6.0,1.0,1.0,8.0,14.0,95.0
3,epistulae ad brutum,1382.0,78.0,19.0,26.0,11.0,56.0,3.0,3.0,3.0,...,9.0,19.0,18.0,3.0,16.0,10.0,11.0,40.0,58.0,220.0
4,pro balbo,696.0,79.0,5.0,25.0,7.0,37.0,2.0,1.0,0.0,...,4.0,4.0,2.0,2.0,0.0,0.0,1.0,3.0,5.0,128.0

In [49]:
df.to_csv('clausulae_data_chkpt1.csv')